"""§5.3 journal columns. Missing value is None, not invented."""

from __future__ import annotations

from typing import Any

from capitalizator.hyexec.features import NAMES as HYEXEC_FEATURE_NAMES

JOURNAL_KEYS = (
    "zone_id",
    "touch_ts",
    "trade_px",
    "trade_qty",
    "session_name",
    "session_hour_utc",
    "prior_session_hi",
    "prior_session_lo",
    "poc",
    "vah",
    "val",
    "fib_trend",  # schema only — no algorithm in this release
    "fib_in_05_1",
    "fib_in_ote_gold",
    "rsi_tf",
    "rsi_value",
    "fvg_present",
    "sweep_wick",
    "htf_h4",
    "htf_d1",
    "cav_label",
    "cav_tf",
    "bar_quality",
    "w_now",
    "w_rank",
    "zlg_label",
    "A_same",
    "A_back",
    "A_in",
    "A_opp",
    "tape_eaten",
    "ofi",
    "trades_in_window",
    "wall_state",
    "refill_proxy",
    "prs_tau",
    "prs_y",
    "gex_bg",
    "btc_state",
    "btc_break_against",
    "card_id",
    "bearing_verdict",
    "first_fact",
    "n_cav",
    "n_zlg",
    "jury",
    "shadow_would",
    "shadow_side",
    "shadow_tag",
    "challenger_would",
    "challenger_tag",
    "skip_reason",
    "outcome",
    "rho_class_id",
    # ОКО — INVENTION-OKO §6. oko_voice is the sixth jury input.
    "oko_voice",
    "oko_label",
    "oko_regime",
    "oko_reason",
    "oko_book_trust",
    "oko_tape_trust",
    "oko_cp_prob",
    "oko_p_bounce",
    "oko_p_break",
    "oko_p_die",
    "oko_set",
    "oko_n_class",
    "oko_size_mult",
    "oko_fingerprint",
    "oko_footprint",
    "oko_footprint_side",
    "oko_oi_z",
    "oko_liq_rel",
    "book_plus",
    "would_aplus",
    "hyexec_as_of",
) + tuple(f"hx_{name}" for name in HYEXEC_FEATURE_NAMES)

KNOWLEDGE_TABLES = (
    "meta",
    "hash_links",
    "episodes",
    "reports",
    "journal_touches",
    "intent_queue",
    "order_queue",
    "overlay",
    "market_event",
    "zone",
    "claim",
    "author_call",
    "news",
    "saved_r",
)


def empty_journal() -> dict[str, Any]:
    return {key: None for key in JOURNAL_KEYS}
